// 获取在线人员
export const QUERY_USER_IN_MANAGERS = 'QUERY_USER_IN_MANAGERS';
// 查询当前登录用户是否为项目经理
export const IS_PROJECT_MANAGER = 'IS_PROJECT_MANAGER';
// 获取项目列表
export const QUERY_PROJECTS_LIST = 'QUERY_PROJECTS_LIST';
// 获取KPI原始数据的列表-需求响应及时率
export const QUERY_REQUIREMENT_RESPONSE_SOURCE_DATA = 'QUERY_REQUIREMENT_RESPONSE_SOURCE_DATA';
// 获取KPI原始数据的列表--需求平均完成率
export const QUERY_REQUIREMENT_FINISHED_SOURCE_DATA = 'QUERY_REQUIREMENT_FINISHED_SOURCE_DATA';
// 获取KPI原始数据的列表-大视频定制需求平均完成率
export const QUERY_VIDEO_REQUIREMENT_FINISHED_SOURCE_DATA = 'QUERY_VIDEO_REQUIREMENT_FINISHED_SOURCE_DATA';
// 获取首页KPI指标--我负责的项目列表
export const QUERY_KPI_MY_PROJECTS_LIST = 'QUERY_KPI_MY_PROJECTS_LIST';
// 获取首页质量度量两个列表，根据传参类型区分两个列表
export const QUERY_HOME_QUALITY_DIMENSION_DATA_LIST = 'QUERY_HOME_QUALITY_DIMENSION_DATA_LIST';
// 获取首页问题工单两个列表，根据传参类型区分两个列表
export const QUERY_HOME_QUESTION_WORK_ORDER_LIST = 'QUERY_HOME_QUESTION_WORK_ORDER_LIST';
// 获取KPI指标-达标情况的列表-需求响应及时率
export const QUERY_KPI_REACH_TIMELY_DATA = 'QUERY_KPI_REACH_TIMELY_DATA';
// 获取KPI指标-达标情况的列表-需求平均完成率
export const QUERY_KPI_REACH_FINISHED_DATA = 'QUERY_KPI_REACH_FINISHED_DATA';
// 获取KPI指标-达标情况的列表-大视频定制化需求完成率
export const QUERY_KPI_REACH_VIDEO_FINISHED_DATA = 'QUERY_KPI_REACH_VIDEO_FINISHED_DATA';
// 获取问题工单原始数据的列表
export const QUERY_QUESTION_ORIGIN_DATA_LIST = 'QUERY_QUESTION_ORIGIN_DATA_LIST';
// 获取整体得分的数据列表
export const QUERY_WHOLE_SCORE_DATA_LIST = 'QUERY_WHOLE_SCORE_DATA_LIST';
// 获取维度测试的数据列表
export const QUERY_DIMENSION_TEST_DATA_LIST = ' QUERY_DIMENSION_TEST_DATA_LIST';
// 获取维度运维的数据列表
export const QUERY_DIMENSION_OPERATION_DATA_LIST = ' QUERY_DIMENSION_OPERATION_DATA_LIST';
// 获取维度开发的数据列表
export const QUERY_DIMENSION_DEVELOP_DATA_LIST = ' QUERY_DIMENSION_DEVELOP_DATA_LIST';
// 获取生产率录入-指标的数据列表
export const QUERY_PRODUCTIVITY_ENTRY_CATEGORY_DATA_LIST = 'QUERY_PRODUCTIVITY_ENTRY_CATEGORY_DATA_LIST';
// 获取生产率录入-人力的数据列表
export const QUERY_PRODUCTIVITY_ENTRY_HUMAN_DATA_LIST = 'QUERY_PRODUCTIVITY_ENTRY_HUMAN_DATA_LIST';
// 获取生产率度量-生产率管理-数据页列表
export const QUERY_PROJECT_STATISTIC_STATUS = 'QUERY_PROJECT_STATISTIC_STATUS';
// 获取生产率度量-生产率管理-管理页列表
export const QUERY_MANAGE_PAGE_LIST = 'QUERY_MANAGE_PAGE_LIST';
// 查询生产率管理是否为超管、QA
export const PRODUCT_USER_PRIVILEGE = 'PRODUCT_USER_PRIVILEGE';
// 生产率度量录入页面中根据用户权限获取项目列表
export const QUERY_PRODUCT_INPUT_PROJECTS = 'QUERY_PRODUCT_INPUT_PROJECTS';
// 查询生产率度量指标类型
export const QUERY_ITEM_TYPE = 'QUERY_ITEM_TYPE';
// 查询生产率度量人力类型
export const QUERY_STAFF_TYPE = 'QUERY_STAFF_TYPE';
// 渲染首页-质量度量-与我有关的大项目列表
export const QUERY_BIG_PROJECTS_BY_MANAGER = 'QUERY_BIG_PROJECTS_BY_MANAGER';
